### ISSUE TITLE
Null-safety migration

### ISSUE THREAD

**Issue by hyungtaecf** [gabrielpacheco23/google-translator#32]
This package is awesome, but since Flutter 2.0 hit the stable branch now it is required to use null-safety.

**Comment by MrAndrixx** [comment]
The last update was made almost 1 year ago, so I don't know if they will update it again. That's why I decided to update it. Also it required `http: ^0.13.0`.

If you want to use it, I'll leave you the repository. You just have to change this:
```
dependencies:
  translator: ^0.1.5
```

With this:
```
dependencies:
  translator:
    git:
      url: git://github.com/MrAndrixx/google-translator
      ref: master
```
